PRAGMA foreign_keys = ON;
DROP TABLE IF EXISTS Waitlist;
CREATE TABLE IF NOT EXISTS Waitlist (
	Email TEXT PRIMARY KEY,
	Code TEXT UNIQUE,
	ReferredBy TEXT,
	CreatedAt TEXT NOT NULL,
	FOREIGN KEY(ReferredBy) REFERENCES Waitlist(Email) ON DELETE SET NULL
);
